module.exports = {
  apps: [
    {
      name: "xml-feed",
      script: "./src/server.js",
      instances: 1,
      exec_mode: "fork",
      node_args: "--max-old-space-size=6144 --max-semi-space-size=2048 --expose-gc",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      max_memory_restart: "5G",
      watch: false,
      ignore_watch: ["node_modules", "data", "screenshots", "logs"],
      error_file: "./logs/err.log",
      out_file: "./logs/out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_restarts: 10,
      min_uptime: "10s",
      autorestart: true,
      kill_timeout: 5000,
    },
    {
      name: "xml-feed-worker",
      script: "./src/workers/clickWorker.js",
      instances: 1,
      exec_mode: "fork",
      node_args: "--max-old-space-size=8192 --max-semi-space-size=3072 --expose-gc",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "7G",
      watch: false,
      ignore_watch: ["node_modules", "data", "screenshots", "logs"],
      error_file: "./logs/worker-err.log",
      out_file: "./logs/worker-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_restarts: 10,
      min_uptime: "10s",
      autorestart: true,
      kill_timeout: 10000,
    },
    {
      name: "xml-feed-scheduler",
      script: "./src/feed-scheduler.js",
      instances: 1,
      exec_mode: "fork",
      node_args: "--max-old-space-size=2048 --expose-gc",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "1.8G",
      watch: false,
      ignore_watch: ["node_modules", "data", "screenshots", "logs"],
      error_file: "./logs/scheduler-err.log",
      out_file: "./logs/scheduler-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      max_restarts: 10,
      min_uptime: "10s",
      autorestart: true,
      kill_timeout: 5000,
    },
  ],
};